# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'TheMovieApp' do
    pod 'Alamofire'
end

target 'TheMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
 
end

target 'TheMovieAppUITests' do
    # Pods for testing
end