# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'TheMovieApp' do
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'Alamofire'
    pod 'RxAlamofire'
end

target 'TheMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
 
end

target 'TheMovieAppUITests' do
    # Pods for testing
end